### ISSUE TITLE
Use of "open" (turn on?) for lights

### ISSUE THREAD

**Issue by gbraad** [japaniot/japaniot.github.io#4]
I realise this is written by an Asian, as the term to "open" and "close" the light seem to be similar to how Chinese say "开" and "关" for turning "on" and "off" a light. The reason why this is confusing as the terms "open circuit" and "closed circuit" can also mean to be "turned off" or "turned on"  in electronics (and therefore the opposite) of what you meant.

**Comment by gbraad** [comment]
@zcbenz

**Comment by zcbenz** [comment]
Fixed with c546d8f, thank you!
